### ISSUE TITLE
在miui和华为魅族等国产rom上效果怎么样？

### ISSUE THREAD

**Issue by sungerk** [laobie/StatusBarUtil#1]

**Comment by laobie** [comment]
目前我没设备，暂时还不知道效果，等我有设备我测测

**Comment by laobie** [comment]
魅族Android 5.1 版本目前是正常的，和原生5.1没差别

**Comment by sungerk** [comment]
明天我倒公司测一样。之前我试过不少类似工具库，但是一到国产rom上就不忍直视

**Comment by laobie** [comment]
有劳了，测试完可以提供截图最好😂

**Comment by yanhaogoogle** [comment]
![device-2016-03-28-094553](https://cloud.githubusercontent.com/assets/5484163/14070706/956c08a6-f4dc-11e5-8f27-a7900e534fe7.png)
![device-2016-03-28-094607](https://cloud.githubusercontent.com/assets/5484163/14070714/ab781a22-f4dc-11e5-8d58-2ba171a953bf.png)
![device-2016-03-28-094627](https://cloud.githubusercontent.com/assets/5484163/14070715/ac32a504-f4dc-11e5-95e6-b4febdcc24ac.png)
这应该不正常吧

**Comment by laobie** [comment]
@yanhaogoogle 刚才看了下，这个是华为的问题，包括现在的emui 4.0 上的状态栏都不是原生的，自己做了修改的，这个目前做不到兼容的。

**Comment by yanhaogoogle** [comment]
@laobie 好的，谢谢，我也是随手测试了一下

**Comment by sungerk** [comment]
测了mi3 ，vivo正常。

**Comment by laobie** [comment]
ok 谢谢了

**Comment by ahangchen** [comment]
@sungerk 小米和华为的工程师应该也是这样想的

**Comment by laobie** [comment]
@sungerk 牛逼 红红火火恍恍惚惚

**Comment by sungerk** [comment]
华为小米的工程师肯定没这么傻屌，傻屌的是那些让程序员乱改rom的人。完全无视谷歌协议不怀好意地修改rom

**Comment by MIkeeJY** [comment]
国产ROM 比如华为 vivo 乐视神马的 底层改动太多 要想兼容根本不可能！还是放弃了。。

**Comment by sweethearting** [comment]
7.0系统原生手机上 没有效果

**Comment by laobie** [comment]
@sweethearting 
![image](https://cloud.githubusercontent.com/assets/7184320/18771946/9f368110-8175-11e6-9036-4686a2e75691.png)
demo 在 7.0 的模拟器上是正常的，真机上 demo 正常不？

**Comment by sweethearting** [comment]
你把构建版本和编译版本换成
compileSdkVersion 24
buildToolsVersion "24.0.1" 

再试试，换成23的可以用，24的就不行了

**Comment by laobie** [comment]
@sweethearting 我 demo 就是用的 24 = =
https://github.com/laobie/StatusBarUtil/blob/master/sample/build.gradle

**Comment by laobie** [comment]
@sweethearting 你什么机型呢？
