### ISSUE TITLE
Fragment中如何实现全透明效果？

### ISSUE THREAD

**Issue by xiang23** [laobie/StatusBarUtil#103]
因为项目是一Activity多Fragment的，我想在其中一个Fragment达到StatusBarUtil.setTranslucentForImageViewInFragment(AccountActivity.this,0,null);的效果应该如何实现？
我现在的做法是
StatusBarUtil.setTranslucentForImageViewInFragment(AccountActivity.this,null);
然后在Fragment中设置View的背景色
setBackgroundColor(Color.argb(0,0,0,0))
但是并不能达到效果

**Comment by laobie** [comment]
你可以参考下 demo 中的 use in fragment 的代码

**Comment by xiang23** [comment]
设置StatusBarUtil.setTranslucentForImageViewInFragment(AccountActivity.this,0,null)，然后除了那个Fragment之外其他Fragment设置为半透明这样？

**Comment by xiang23** [comment]
另外问下能只设置状态栏为半透明而不更改虚拟键盘颜色吗？

**Comment by laobie** [comment]
不可以
