### ISSUE TITLE
DrawerLayout中按钮触发mainActivity的statusbar变色失败

### ISSUE THREAD

**Issue by hxingever** [laobie/StatusBarUtil#105]
好吧 可能是之前没有描述清楚 我是用的系统侧滑DrawerLayout，在侧边栏有个按钮控制mainActivity的statausbar改变颜色，我调的StatusBarUtil.setColorForDrawerLayout（）方法但是没有成功..默认第一次进来加色是正常的.

**Comment by laobie** [comment]
你在我的 demo 的 MainActivity 中 自己加几行代码就能测一下的事情，为嘛非要来一个个问呢？
我的答案是可以的。

GitHub 是大家分享代码的地方，希望你自己也能多实践下。
![image](https://cloud.githubusercontent.com/assets/7184320/23388257/16aacd9e-fd9c-11e6-9c77-49108117efc0.png)
