### ISSUE TITLE
StatusBarUtil.setTranslucentForImageViewInFragment bug 状态栏不透明

### ISSUE THREAD

**Issue by wangdroid** [laobie/StatusBarUtil#108]
主界面为底部导航栏+5个fragment,有个界面头部是ImageView,但是设置后，状态栏没有透明，图片没有延伸出去

**Comment by laobie** [comment]
你看看 demo 中的那个 Fragment 中的使用示例。

**Comment by wangdroid** [comment]
设置了不起作用，没用toolbar，我看demo用的是ViewPager进行切换
![s90c v b02knqx0v g f 1](https://cloud.githubusercontent.com/assets/4505504/23979915/6f00b7c2-0a37-11e7-92ec-cb4ab618afa1.png)

**Comment by laobie** [comment]
你用的是哪个方法

**Comment by wangdroid** [comment]
StatusBarUtil.setTranslucentForImageViewInFragment

**Comment by laobie** [comment]
https://github.com/laobie/StatusBarUtil/blob/master/sample/src/main/java/com/jaeger/statusbarutil/UseInFragmentActivity.java

建议再看看这里的处理思路，和你的效果是一致的， toolbar 用没用没影响的
