### ISSUE TITLE
华为有虚拟按键的设备上，状态栏不透明（无效）

### ISSUE THREAD

**Issue by YY007H** [laobie/StatusBarUtil#109]
最开始我还以为我设置的有问题，结果我直接下demo测试，在华为设备无效，都是黑色的

**Comment by huanting** [comment]
我测试没有发现问题，不知道你测试华为哪个设备？我测试的是mate 8,  测试demo中的“Set Transparent”.

**Comment by YY007H** [comment]
稍等 给你上图 设备为HUAWEI M2-A01L

**Comment by YY007H** [comment]
![Uploading Screenshot_2017-03-20-10-50-33.png…]()
![Uploading Screenshot_2017-03-20-10-49-58.png…]()
![Uploading Screenshot_2017-03-20-10-49-48.png…]()

**Comment by laobie** [comment]
之前测过部分华为机器， emui 4.0 来着，好像是可以的

**Comment by YY007H** [comment]
![screenshot_2017-03-20-10-50-33](https://cloud.githubusercontent.com/assets/15188456/24087565/856e8738-0d5b-11e7-87e5-99ee6a35b701.png)
![screenshot_2017-03-20-10-49-58](https://cloud.githubusercontent.com/assets/15188456/24087560/847a0bcc-0d5b-11e7-821d-bf14e3bb9428.png)
![screenshot_2017-03-20-10-49-48](https://cloud.githubusercontent.com/assets/15188456/24087561/84b51884-0d5b-11e7-8b38-f9bfab803292.png)

**Comment by YY007H** [comment]
这个设备是 emui 4.0   系统是Android5.1

**Comment by laobie** [comment]
感觉这种问题只能归为厂商的问题了😂 不知道他们改了啥东西

**Comment by YY007H** [comment]
但是compile 'com.readystatesoftware.systembartint:systembartint:1.0.3' 这个可以正常使用

**Comment by laobie** [comment]
。。。不一样的实现方式啊，你这种说法和产品一个思路: iOS 能做到啊

**Comment by YY007H** [comment]
好吧 我看它是用反射直接修改底层属性 的确不太一样

**Comment by YY007H** [comment]
找到一种解决方式，都使用decorView进行处理  即可实现透明。难道华为的系统只是把版本号换了而已。。。
![qq 20170320125048](https://cloud.githubusercontent.com/assets/15188456/24088966/e503c522-0d6b-11e7-8994-f4219e309a38.png)

**Comment by YY007H** [comment]
我把所有的LOLLIPOP改成M了，在这个设备上完全可以，我再尝试一些别的设备，好坑的感觉

**Comment by laobie** [comment]
啊哈哈哈 华为改版本号升级的？

**Comment by liunewshine** [comment]
![Uploading device-2017-03-24-135811.png…]()
![Uploading device-2017-03-24-135833.png…]()
华为手机确实无效

**Comment by liunewshine** [comment]
![device-2017-03-24-135811](https://cloud.githubusercontent.com/assets/7698511/24282442/63b44f6e-109a-11e7-8da5-2c4bb4459bdd.png)
![device-2017-03-24-135833](https://cloud.githubusercontent.com/assets/7698511/24282448/6caebbf4-109a-11e7-811b-ac37b41d0e5b.png)
华为手机确实无效

**Comment by YY007H** [comment]
@liunewshine 看我的解决办法  你把VERSIONCODE.LOLLIPOP改成VERSIONCODE.M  在不少机型上测试通过

**Comment by laobie** [comment]
> 你把VERSIONCODE.LOLLIPOP改成VERSIONCODE.M 在不少机型上测试通过 

这个所谓的不少机型 应该都是华为吧。。。

**Comment by YY007H** [comment]
@laobie 没有啊 反正华为的设备有毒 不过6.0以上的不受影响 6.0以下的还是用老办法整吧

**Comment by laobie** [comment]
对于华为这种，我是不太乐意兼容的。

**Comment by YY007H** [comment]
@laobie 大佬啊 你试试把系统版本号判断提高一版  看看会不会别的设备的5.0和5.1就用了不了  我就只有华为和小米的 我这边测试是可以正常显示透明

**Comment by laobie** [comment]
两个不一样的实现方式，全版本都可以用 4.4 那样的实现。重点是那个分届点是按照官方的标准来，我不可能因为华为而改这个。换句话说，我不会在代码中写 `isHuawei` 这种的判断。所以你如果需要兼容华为改版本号升级的系统，你可以 fork 回去，自己修改，我这边不会做改动的。

**Comment by YY007H** [comment]
我对比了SystemBarTint的代码 它的是全用替换的方式修改透明 也就跟我说的差不多  5.0和5.1分界点 官方只是把接口暴露出来了 华为等部分厂商可能觉得不好又给屏蔽了   如果只判断6.0和6.0以上的机型  理论上没有问题的

**Comment by liunewshine** [comment]
我对华为也是深恶痛绝，发誓这辈子不买华为
