### ISSUE TITLE
咨询下关于StatusBarUtil设置状态栏后，切换横屏的问题

### ISSUE THREAD

**Issue by wmhqnyh** [laobie/StatusBarUtil#110]
使用StatusBarUtil.setColor(this, getResources().getColor(R.color.xxx),0)后，APP中有视频功能，所以切全屏会出现状态栏的颜色条。

谢谢作者！

**Comment by laobie** [comment]
处理下横竖屏切换，有一个 `hideFakeStatusBarView`  方法可以处理下
