### ISSUE TITLE
toolbar被状态栏遮住

### ISSUE THREAD

**Issue by liunewshine** [laobie/StatusBarUtil#111]
![qq 20170330155335](https://cloud.githubusercontent.com/assets/7698511/24493344/1b8d1b1e-1561-11e7-85b8-3946da8ac28e.png)
![qq 20170330155350](https://cloud.githubusercontent.com/assets/7698511/24493358/20e44150-1561-11e7-97b3-357684814268.png)
![device-2017-03-30-155201](https://cloud.githubusercontent.com/assets/7698511/24493372/28260c78-1561-11e7-898e-04104c2080ca.png)
![device-2017-03-30-155305](https://cloud.githubusercontent.com/assets/7698511/24493378/2d4ce06e-1561-11e7-8c01-accc8456a09b.png)

怎么办呢？

**Comment by laobie** [comment]
下载 demo ，测试下 demo 是否正常

**Comment by liunewshine** [comment]
@laobie demo是正常的，我自己找找原因吧，但是没有这个StatusBarUtil.setColor(this, ContextCompat.getColor(this, R.color.colorPrimary), 1);是正常的

**Comment by laobie** [comment]
如果 demo 是正常的，那就自己找找原因 
你看看主题是不是设置了什么

**Comment by liunewshine** [comment]
因为我StatusBarUtil.setColor以后又调用了一遍setContentView导致的
