### ISSUE TITLE
activity弹出问题

### ISSUE THREAD

**Issue by zhupengxiang** [laobie/StatusBarUtil#116]
不知道为什么在4.4.4的手机上用了statusbarutils所有的activity都从底部弹出了  求告知

**Comment by laobie** [comment]
@zhupengxiang 可能是主题问题，你自己检查下，和这个库应该没关系

**Comment by zhupengxiang** [comment]
@laobie   不应该吧  我用demo装在手机上也是一样的

**Comment by laobie** [comment]
那就换别的库吧，这个库不太好用

**Comment by zhupengxiang** [comment]
@laobie  不是吧老哥。

**Comment by laobie** [comment]
是的呢

**Comment by zhupengxiang** [comment]
@laobie   蓝瘦香菇
