### ISSUE TITLE
Typo in the dependency import

### ISSUE THREAD

**Issue by TonyTangAndroid** [laobie/StatusBarUtil#122]
I realize that the current published library compile path is 

`compile 'com.jaeger.statusbaruitl:library:1.3.6'
`
But the `statusbaruitl` is intended to be `statusbarutil` if I am not misinterpreting. Any plan to correct it or leave it be?

**Comment by laobie** [comment]
I am sorry for this mistake, but change it is difficult. I will find a right way to modify this mistake.

**Comment by TonyTangAndroid** [comment]
Thank you for getting back to me. No worry at all.

**Comment by laobie** [comment]
I have fix typo, version 1.4.0 is published

```
compile 'com.jaeger.statusbarutil:library:1.4.0'
```
