### ISSUE TITLE
你好 我用华为的tag-al00 运行demo发现statusbar颜色没有改变

### ISSUE THREAD

**Issue by CallmeJeRrYHo** [laobie/StatusBarUtil#126]
![screenshot_2017-05-09-16-58-33](https://cloud.githubusercontent.com/assets/17061503/25843247/595fd520-34d9-11e7-9131-64da5896e684.png)
![screenshot_2017-05-09-16-58-43](https://cloud.githubusercontent.com/assets/17061503/25843246/595c8974-34d9-11e7-9742-5e8e3c4557ab.png)
![screenshot_2017-05-09-16-58-58](https://cloud.githubusercontent.com/assets/17061503/25843245/595c4694-34d9-11e7-8b03-cff985e64c2c.png)
![screenshot_2017-05-09-17-00-58](https://cloud.githubusercontent.com/assets/17061503/25843248/597fd4d8-34d9-11e7-9d61-a852521e5be8.png)

**Comment by laobie** [comment]
部分国产 rom 没法完美支持的
