### ISSUE TITLE
Build报如下错误

### ISSUE THREAD

**Issue by xxzj990** [laobie/StatusBarUtil#13]
Error:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.2.0) and test app (23.1.0) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

**Comment by laobie** [comment]
需要升级下你的 support 的版本到23.2.0应该就可以了

**Comment by laobie** [comment]
@xxzj990 请问下你后来解决了么？

**Comment by xxzj990** [comment]
@laobie 我的support版本是23.2.1，最新的了。我直接使用源码了，没有这个问题了。
