### ISSUE TITLE
是不是每个Activity都要调用设置颜色方法，能写在Base里吗，那些方法参数我都看不懂什么意思，又没栗子

### ISSUE THREAD

**Issue by guanyueyun** [laobie/StatusBarUtil#130]

**Comment by laobie** [comment]
还需要啥样的例子？下载 demo，那就是例子 。

**Comment by LB-ocean** [comment]
在平板里边就 不可以了，横屏的时候 ，我试过；

**Comment by laobie** [comment]
？啥意思 @LB-ocean

**Comment by LB-ocean** [comment]
我一个同样的程序，在手机端 是OK的，但是我放到 平板里边(1280x800)去运行，状态栏和下边的就会分隔出来,平板android 系统是5.1.1；

**Comment by Mao-x-w** [comment]
当然可以写在BaseActivity中了，在BaseActivity中重写setContentView,然后加上StatusBarUtils.setColor(this, Color.WHITE)所有activity都生效了
