### ISSUE TITLE
小米6.0的手机

### ISSUE THREAD

**Issue by xie3120** [laobie/StatusBarUtil#132]
我用的小米note，系统是6.0.1的，调用 StatusBarUtil.setTranslucent(this);没什么反应

**Comment by laobie** [comment]
@xie3120 先测试下 demo 如果正常的话看下你的使用姿势

**Comment by xie3120** [comment]
我现在项目里面要实现的是，先是沉浸式状态栏，滑动的时候标题栏变白色，状态栏也变白色，状态栏的字变成黑色。这个能实现么。

**Comment by laobie** [comment]
![image](https://user-images.githubusercontent.com/7184320/27209602-5eb9ba72-527f-11e7-99a0-42bdcabce92f.png)

**Comment by laobie** [comment]
1.5 版本已经添加设置状态栏模式方法，请更新到最新版本
```
  StatusBarUtil.setLightMode(Activity activity)
  StatusBarUtil.setDarkMode(Activity activity)
```
