### ISSUE TITLE
状态栏有阴影

### ISSUE THREAD

**Issue by ITzhangyan** [laobie/StatusBarUtil#148]
状态栏有阴影，能去除么？怎么去除？

**Comment by laobie** [comment]
看所有的 demo 截图都是没有的，你确定不是的 toolbar 之类的阴影？

**Comment by ITzhangyan** [comment]
不是，透明状态栏的渐变阴影

**Comment by laobie** [comment]
说实话 我没看懂你在说啥

**Comment by laobie** [comment]
你是在说 4.4 的那个渐变么 那个是没法去掉的

**Comment by ITzhangyan** [comment]
哦，这样啊，我还给你邮箱发了，就是那个渐变

**Comment by ITzhangyan** [comment]
像京东那种是并没有阴影，是怎么做的？

**Comment by laobie** [comment]
有个 alpha 参数，请看 readme 下载 demo 自己测测看，要不了 2 分钟
谢谢

**Comment by laobie** [comment]
![image](https://user-images.githubusercontent.com/7184320/30477392-98da57b2-99d2-11e7-85f0-baf9b1248292.png)
请问你觉得这个有所谓的 “阴影” 么
