### ISSUE TITLE
我想问下，如果是白色为主题色的沉浸式菜单，状态栏为黑色字体。这种场景有没考虑

### ISSUE THREAD

**Issue by PantomZ** [laobie/StatusBarUtil#154]

**Comment by lmdiloveu** [comment]
我靠，我就遇到这个问题，状态栏的文字颜色也是白色的，背景是白色的，怎么修改文字颜色

**Comment by 7hundeR** [comment]
我也准备问这个的  TAT

**Comment by magiclonw** [comment]
https://github.com/scwang90/SmartRefreshLayout/blob/master/app/src/main/java/com/scwang/refreshlayout/util/StatusBarUtil.java 这里的他有个darkmode 可以解决你的问题

**Comment by chenyusheng** [comment]
这也是我想问的，如何修改颜色啊。。。

**Comment by laobie** [comment]
@PantomZ 
@lmdiloveu 
@7hundeR 
@chenyusheng 
@magiclonw 
1.5 版本已经添加设置状态栏模式方法，请更新到最新版本
```
  StatusBarUtil.setLightMode(Activity activity)
  StatusBarUtil.setDarkMode(Activity activity)
```
