### ISSUE TITLE
setColort()方法会导致标题栏变为纯白

### ISSUE THREAD

**Issue by ReisenZ** [laobie/StatusBarUtil#157]
setColor(Activity activity,int color, int statusBarAlpha)
当调用该方法时如果透明度值为0时, 标题栏背景会变为纯白, 只要不传0就能正常显示...
该问题在api21和api25的手机上都会出现...

**Comment by ReisenZ** [comment]
补图
[alpha不为0](https://raw.githubusercontent.com/ReisenZ/update/master/1.png)
[alpha为0](https://raw.githubusercontent.com/ReisenZ/update/master/2.png)

**Comment by vzhilong** [comment]
遇到相同的问题。

**Comment by ReisenZ** [comment]
参数color接收的颜色int值为ARGB, 误传为RGB的int值
