### ISSUE TITLE
希望作者把修改状态栏字体颜色的方法加进来！！！

### ISSUE THREAD

**Issue by 897902334** [laobie/StatusBarUtil#161]
我使用的大神写的库，  项目中用到了白色的主题，  可想而知  这样一来 白色状态栏字体也看不到了  很是不爽！    希望大神把这个方法加进去  谢谢。

**Comment by VictorChow** [comment]
@897902334 6.0以上可以设置深色状态栏字体颜色

**Comment by 897902334** [comment]
@VictorChow   嗯这个我知道，但是6.0之下的呢？还有6.0的其他品牌手机呢，  我现在不用这个库了，已经换了，  用的严大的   https://github.com/yanzhenjie/Sofia
