### ISSUE TITLE
请问下， 好像只能在5.0以上版本有效，4.4版本都无效啊

### ISSUE THREAD

**Issue by fjzboy** [laobie/StatusBarUtil#164]

**Comment by laobie** [comment]
看项目 README 截图，如果你实际测试下来没效果，可能你的手机是华为，可以在 4.4 的模拟器上测试下

**Comment by pwj1568** [comment]
设置状态栏透明的方法在android5.0版本的手机上也无效，

**Comment by caobin821651400** [comment]
@pwj1568 vivo需要6.0

**Comment by laobie** [comment]
vivo 等部分国产机器是有兼容问题的，他们的 Android 版本和同样的 Google Android 版本是有表现上的差别的
