### ISSUE TITLE
关于全面屏适配的问题

### ISSUE THREAD

**Issue by ppg408331701** [laobie/StatusBarUtil#165]
最近18:9的手机越来越多
app中一般都会有启动图,这个启动图是会定期更换的
所以不能以切16:9和18:9的两张图来适配

StatusBarUtil这个库中,启动图要延伸到状态栏的话必须要设置为根布局的背景,但是如果16:9的图设置成背景的话,在18:9的设备上会被拉伸变形
如果用imageview的src设备启动图话又没有办法延伸到状态栏

请问有什么好办法吗?

**Comment by laobie** [comment]
可以使用 imageView 的

**Comment by ppg408331701** [comment]
你是说把imageView当成根布局?
我试过,在小米6 miui9上出现问题
状态栏会有一半出现白条
![screenshot_2017-12-26-14-36-39-704_com webapps yi](https://user-images.githubusercontent.com/16531268/34349151-43a931f0-ea4a-11e7-8a02-0f3c5f36c85a.png)


```
<?xml version="1.0" encoding="utf-8"?>
<ImageView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/fl"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:src="@mipmap/launch"
    android:fitsSystemWindows="true"
    android:scaleType="centerCrop">
</ImageView>```

**Comment by laobie** [comment]
你使用的是哪个方法呢？你使用 `setTranslucentForImageView ` 这个方法试试

**Comment by ppg408331701** [comment]
发现问题了
miui9使用状态栏沉浸的时候会出现这个问题
去掉
this.getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_VISIBLE);
这句就好了

**Comment by laobie** [comment]
好吧
