### ISSUE TITLE
DrawerLayout 改变颜色，上面会多出一条状态栏来

### ISSUE THREAD

**Issue by 7312013787** [laobie/StatusBarUtil#17]
第一次设置颜色是没问题的
![qq 20160607163038](https://cloud.githubusercontent.com/assets/7372078/15850937/37dd7570-2ccd-11e6-9770-77030d9a1368.png)
，第二次想改变颜色就出问题了
![qq 20160607163240](https://cloud.githubusercontent.com/assets/7372078/15850986/7d90c612-2ccd-11e6-9ebf-ec01286b9358.png)

**Comment by laobie** [comment]
方便给下你的布局文件么？

**Comment by laobie** [comment]
@7312013787

**Comment by 7312013787** [comment]
<android.support.v4.widget.DrawerLayout
    android:id="@+id/drawerlayout"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <LinearLayout
        android:id="@+id/ll_content"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#EBEBEB"
        android:orientation="vertical">

        <FrameLayout
            android:id="@+id/realtabcontent"
            android:layout_width="match_parent"
            android:layout_height="0dip"
            android:layout_weight="1"/>

        <android.support.v4.app.FragmentTabHost
            android:id="@android:id/tabhost"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@android:color/white">

            <include layout="@layout/line_gray"/>

            <FrameLayout
                android:id="@android:id/tabcontent"
                android:layout_width="0dp"
                android:layout_height="0dp"
                android:layout_weight="0"/>
        </android.support.v4.app.FragmentTabHost>
    </LinearLayout>

    <include
        layout="@layout/layout_menu"
        android:layout_width="240dp"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        android:tag="LEFT"
        />
</android.support.v4.widget.DrawerLayout>

**Comment by 7312013787** [comment]
<android.support.v4.widget.DrawerLayout
    android:id="@+id/drawerlayout"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <LinearLayout
        android:id="@+id/ll_content"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#EBEBEB"
        android:orientation="vertical">
        <FrameLayout
            android:id="@+id/realtabcontent"
            android:layout_width="match_parent"
            android:layout_height="0dip"
            android:layout_weight="1"/>

        <android.support.v4.app.FragmentTabHost
            android:id="@android:id/tabhost"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@android:color/white">

            <include layout="@layout/line_gray"/>

            <FrameLayout
                android:id="@android:id/tabcontent"
                android:layout_width="0dp"
                android:layout_height="0dp"
                android:layout_weight="0"/>
        </android.support.v4.app.FragmentTabHost>
    </LinearLayout>

    <include
        layout="@layout/layout_menu"
        android:layout_width="240dp"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        android:tag="LEFT"
        />
</android.support.v4.widget.DrawerLayout>

**Comment by 7312013787** [comment]
![qq 20160607174628](https://cloud.githubusercontent.com/assets/7372078/15853491/cf195d32-2cd7-11e6-8754-e11c5201cf88.png)
应该是在这里重复添加了

**Comment by laobie** [comment]
@7312013787 你加一下我qq 254158532 你的布局中没有 drawerLayout？

**Comment by laobie** [comment]
fixed
