### ISSUE TITLE
状态栏设置白色无效

### ISSUE THREAD

**Issue by cjcj125125** [laobie/StatusBarUtil#187]
如题，状态栏设置白色，显示出来是灰色的，什么鬼？？

**Comment by cjcj125125** [comment]
下载了你的demo运行了一下，状态栏设置白色之后就看不到信号，电量等信息了，因为这些信息本来也是白色的，但是看了下知乎app和知识星球app，他们的状态栏是白色的时候电量之类的信息会变成黑色，请问大佬这是怎么实现的？？？

**Comment by laobie** [comment]
`
  StatusBarUtil.setLightMode(Activity activity)
  StatusBarUtil.setDarkMode(Activity activity)
`
多花点时间阅读下文档
