### ISSUE TITLE
晕，为什么我就是没效果？？

### ISSUE THREAD

**Issue by vihuela** [laobie/StatusBarUtil#19]
StatusBarUtil.setTransparent(this);
StatusBarUtil.setTranslucent(this, StatusBarUtil.DEFAULT_STATUS_BAR_ALPHA);
状态栏都是白茫茫的一条，style文件设置了，找不到原因

**Comment by laobie** [comment]
@vihuela 这个是设置透明，你需要设置你的根布局为一张图时使用，你可以下载 demo 看看
