### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by LuigiBaute** [laobie/StatusBarUtil#190]
Hello! I would like to collaborate with this project by providing a _free_ new logo that suits with the project! Let me know if interested so we can get in touch.

**Comment by laobie** [comment]
Hello! I am very happy to know this, you can send the logo file to my mailbox: im.houzi@gmail.com.

**Comment by laobie** [comment]
@LuigiBaute thank you, you can contact me with telegram  [laobie](https://t.me/laobie)

**Comment by LuigiBaute** [comment]
greetings @laobie this is what I came up with, I hope you like it!
![logotipo statusbar 2018](https://user-images.githubusercontent.com/36426974/40036887-181516c0-57d8-11e8-8797-2e9cb34a322d.jpg)
![logotipo statusbar 2018 3](https://user-images.githubusercontent.com/36426974/40036900-371dbaea-57d8-11e8-9acf-ae52b0175059.jpg)

If you like any of these, I'll upload it in a pull request!

**Comment by laobie** [comment]
![image](https://user-images.githubusercontent.com/7184320/40038003-980c965e-5842-11e8-8080-c08a686c4d7f.png)
The green one. Thanks.
