### ISSUE TITLE
等了半年，貌似还没解决键盘问题？

### ISSUE THREAD

**Issue by ruanbaojun1105** [laobie/StatusBarUtil#192]
········虽然找到比这更好的库

**Comment by laobie** [comment]
等着你们提 pr 呢

**Comment by ruanbaojun1105** [comment]
# [`**不提，不用，哼******`](url)

**Comment by laobie** [comment]
![image](https://user-images.githubusercontent.com/7184320/39183717-86ff1800-47f3-11e8-8be3-634c6e85ece7.png)
哪个更好的库呢？我学习一发

**Comment by ruanbaojun1105** [comment]
@laobie ImmersionBar,去抄吧。

**Comment by laobie** [comment]
@ruanbaojun1105  说的真难听，伸手还这么理直气壮？？对你们这些伸手党开发者真的很无语。爱用不用。再见。
