### ISSUE TITLE
魅族手机会出现双层的

### ISSUE THREAD

**Issue by darkSuperman** [laobie/StatusBarUtil#195]
老哥，魅族手机会出现这个情况，就使用了 StatusBarUtil.setColor( getActivity(),getResources().getColor(R.color.titlebar_color));
是再baseFragment里面写的。魅族安卓5.1。
还有就是为什么我魅族的手机布局会从状态栏开始布局，始终整体布局最下面会留有一个状态栏的高度
求救，都折腾我好久了。

**Comment by darkSuperman** [comment]
![aaa](https://user-images.githubusercontent.com/23699296/39224732-59129d30-487b-11e8-82a0-7233009457f8.png)

**Comment by treanow** [comment]
你看清demo的用法啊,DemoFragment里面就没有用过StatusBarUtil.setColor,你看看UseInFragmentActivity怎么写的
