### ISSUE TITLE
calculateStatusColor 方法的一些疑问

### ISSUE THREAD

**Issue by Muxter** [laobie/StatusBarUtil#198]
```
private static int calculateStatusColor(@ColorInt int color, int alpha) {
        if (alpha == 0) {
            return color;
        }
        float a = 1 - alpha / 255f;
        int red = color >> 16 & 0xff;
        int green = color >> 8 & 0xff;
        int blue = color & 0xff;
        red = (int) (red * a + 0.5);
        green = (int) (green * a + 0.5);
        blue = (int) (blue * a + 0.5);
        return 0xff << 24 | red << 16 | green << 8 | blue;
}
```
calculateStatusColor 方法只是用传入的 alpha 对原 color 计算了一个比例，实际上并没有设置 alpha 通道的值。返回的 color 的 alpha 部分总是 `ff`。如果只是这样的话，alpha参数应该去掉，而不是这样误导。
这个参数最后是被setColor 方法调用的，这会让人误解

另外我注意到系统的 setStatusBarColor() 方法对于含有透明度的颜色并不生效，只是显示其剥离透明度后的颜色值，所以这个方法如此计算颜色值是这个原因么？

**Comment by laobie** [comment]
这个只是计算出那种半透明的遮罩的效果，状态栏要是真的半透明，那可以看到屏幕上的电路板么………这个方法的具体作用你可能不理解，你要是下个 demo 看看这个方法的作用就不会这么问了。
