### ISSUE TITLE
有个问题想请教

### ISSUE THREAD

**Issue by Zhangxd77** [laobie/StatusBarUtil#199]
我想实现的是mainActivity状态栏为纯色，抽屉顶部为图片，状态栏为透明效果
我是使用的drawerLayout,刚进入的时候写  
`
  StatusBarUtil.setColor(this, getResources().getColor(R.color.red_primary), 0);
 StatusBarUtil.setTranslucentForDrawerLayout(MainActivity.this, drawerLayout, 0);
`      
状态栏的颜色不会变成我设置的颜色，会是colors中的colorPrimary颜色，并且4.4的测试机抽屉顶部不能透明，图片延伸不上去。请问这个怎么解决？谢谢，或者您有对mainActivity状态栏为纯色，抽屉顶部为图片，状态栏为透明效果别的解决办法，告诉我一下，谢谢

**Comment by laobie** [comment]
哥们 下载 demo 看一眼，你就知道你要的效果了
