### ISSUE TITLE
在gradle里面引用以后，报错，烦劳大神给解答一下

### ISSUE THREAD

**Issue by BeforeFuture** [laobie/StatusBarUtil#200]
在gradle里面引用以后，报错，烦劳大神给解答一下。
百度+Google了很多方法都不行。

Information:Gradle tasks [:app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources, :calendarlibrary:generateDebugSources, :calendarlibrary:mockableAndroidJar, :calendarlibrary:prepareDebugUnitTestDependencies, :calendarlibrary:generateDebugAndroidTestSources]
Warning:The `android.dexOptions.incremental` property is deprecated and it has no effect on the build process.
D:\workspace\sfdj-android\app\build\intermediates\res\merged\debug\values-v26\values-v26.xml
Error:(15, 21) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
Error:(18, 21) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
Error:(15, 21) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
Error:(18, 21) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by laobie** [comment]
你这个报错在移除我这个库后就正常了么？

**Comment by BeforeFuture** [comment]
屏蔽引用后就ok了，我测试了3遍，都这样。
试着以lib形式引用，又出现了其他的问题。。。

**Comment by laobie** [comment]
@BeforeFuture 估计是 support 库版本不一致，你可以 exclude support lib 试试，或者直接拷代码使用好了
