### ISSUE TITLE
关于setTransparent的用法

### ISSUE THREAD

**Issue by hnty545** [laobie/StatusBarUtil#201]
是不是Transparent的方式必须根控件要有背景色或者背景图的呢，我有个自制的标题栏，又不想用setColor，请问有方法自动识别我的标题栏色吗？

**Comment by hnty545** [comment]
其实多数时候根控件都没有背景色或者是白色，也没有背景图的，所以这个透明方法地位有点尴尬

**Comment by laobie** [comment]
`setTransparent()` 这个方法的场景有限，你这个需求还是 setColor 比较好，你可以放在 baseActivity 中做，比如 `setColor(this, cuctomTitleBar.getColor())`

**Comment by laobie** [comment]
这是 feature 不是 bug = =

**Comment by laobie** [comment]
滑动一下状态栏就没了，也很奇怪吧，你这个可以把状态栏的图标设置成黑色的 `setLightMode()`

**Comment by hnty545** [comment]
不是的，主页我设置的红色的，和那块背景一致，但是拖动变成黑色了，就有点奇怪

**Comment by hnty545** [comment]
不是的，主页我设置的红色的，和那块背景一致，但是拖动变成黑色了，就有点奇怪

**Comment by hnty545** [comment]
@laobie
