### ISSUE TITLE
页面切换，状态栏文字会闪一下

### ISSUE THREAD

**Issue by chinahbpyj** [laobie/StatusBarUtil#203]
你好，我设置状态栏字体的颜色如果都是黑色，页面间切换，状态栏文字会闪一下或者可以看到状态栏字体先为白色然后变成了黑色，要是上一个页面状态栏字体是黑色，下一个页面状态栏字体为白色，状态栏文字则不会闪一下。

**Comment by laobie** [comment]
@chinahbpyj 问题解决了啊？

**Comment by chinahbpyj** [comment]
我又测试了别的机型，目前就我用的（红米note4想）有这个问题

**Comment by laobie** [comment]
哦哦 那可能是部分机型的适配问题了

**Comment by xyang020** [comment]
我测试的小米5手机也有这个问题，有解决办法吗？
