### ISSUE TITLE
一个Act里面放四个Fragment这样的方式如何设置图片状态栏啊?

### ISSUE THREAD

**Issue by 282167361** [laobie/StatusBarUtil#207]
很古老的代码,他的fragment是这样的,这样如何设置状态栏?

   <RelativeLayout
        android:layout_width="match_parent"
        android:fitsSystemWindows="true"
        android:layout_marginBottom="50dp"
        android:layout_height="match_parent" >

        <fragment
            android:id="@+id/frag_one"
            android:name="com.yayun.project.base.pengbaoshop.app.fragment.tabone.TabOneAFragment"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <fragment
            android:id="@+id/frag_two"
            android:name="com.yayun.project.base.pengbaoshop.app.fragment.tabtwo.TabTwoAFragment"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <fragment
            android:id="@+id/frag_three"
            android:name="com.yayun.project.base.pengbaoshop.app.fragment.tabthree.TabThreeBFragment"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <fragment
            android:id="@+id/frag_five"
            android:name="com.yayun.project.base.pengbaoshop.app.fragment.tabfive.TabFiveBFragment"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </RelativeLayout>

**Comment by laobie** [comment]
没有办法，能力有限。
