### ISSUE TITLE
5.0+部分手机不能呈现沉浸式效果

### ISSUE THREAD

**Issue by Aelous-6** [laobie/StatusBarUtil#21]
本人手里有部Samsung A8000, 在这台手机上是你作者你写的setColor方法不能实现沉浸式效果，这个方法不能适用于手机5.0+的手机吗

**Comment by laobie** [comment]
看 readme 中的截图，对于大部分手机都是支持的，部分厂商改了系统底层的话，是没法兼容的，这个不是 bug

**Comment by Aelous-6** [comment]
嗯。判断Build.VERSION.SDK_INT大于等于LOLLIPOP可以直接调用setStatusBarColor()方法直接设置状态栏颜色就行了。

**Comment by laobie** [comment]
@Aelous-6 你用的哪个方法，我代码里面5.0及其以上也是直接用系统提供的api的
