### ISSUE TITLE
状态栏透明后，下方

### ISSUE THREAD

**Issue by hnty545** [laobie/StatusBarUtil#210]

**Comment by laobie** [comment]
？

**Comment by hnty545** [comment]
状态栏透明后下方导航栏也透明了，似乎是transparentStatusBar中activity.getWindow().addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION);导致的，注释这一句又导致状态栏也不透明了

**Comment by hnty545** [comment]
其实我不太理解你的setTransparent中为什么要setRootView的setFitsSystemWindows(true)，这样状态栏透明以后空出来了，界面没有上下拉伸来填充空白，我现在用的时候这个方法是注销的，然后对跟有背景图的节点设置paddingTop来达到拉伸到状态栏的效果。

但对于有下方虚拟导航栏的机器，下方虚拟导航栏也同样透明而挡住界面，我试过对根节点也设置paddingBottom，但是无法检测这个下方虚拟导航栏是否隐藏，现在很头疼，暂时用你的setColor来解决取一个近似色，但对于背景是整张图片的情况，效果就比较差了。

**Comment by downtail** [comment]
> 其实我不太理解你的setTransparent中为什么要setRootView的setFitsSystemWindows(true)，这样状态栏透明以后空出来了，界面没有上下拉伸来填充空白，我现在用的时候这个方法是注销的，然后对跟有背景图的节点设置paddingTop来达到拉伸到状态栏的效果。
> 
> 但对于有下方虚拟导航栏的机器，下方虚拟导航栏也同样透明而挡住界面，我试过对根节点也设置paddingBottom，但是无法检测这个下方虚拟导航栏是否隐藏，现在很头疼，暂时用你的setColor来解决取一个近似色，但对于背景是整张图片的情况，效果就比较差了。

遇到一样的问题，有好的解决方法吗
