### ISSUE TITLE
通过StatusBarUtil.setColor无法设置成白色，会显示成深灰色

### ISSUE THREAD

**Issue by Leu-Z** [laobie/StatusBarUtil#220]
通过StatusBarUtil.setColor无法设置成白色，会显示成深灰色

**Comment by 1595901624** [comment]
将透明度设为0

**Comment by Leu-Z** [comment]
设置成#00FFFFFF，还是灰色的

**Comment by Leu-Z** [comment]
谢谢你，可以了， 没仔细看源码

**Comment by AndMy** [comment]
设置白色后，状态栏字体怎么变暗色

**Comment by AndMy** [comment]
看到了

**Comment by 1595901624** [comment]
客气，共同进步 @Leu-Z

**Comment by huangchaoqingcheng** [comment]
请问一下
我设置StatusBarUtil.setColor(this, getResources().getColor(R.color.white), 0);后状态栏是变成白色了 但是字体就看不清了  我接着调 StatusBarUtil.setLightMode(this); 字体是变白了  但是布局延伸到状态栏上去了。。。。你们没有碰到这种情况吗

**Comment by laobie** [comment]
设置 `fitSystemWindow = true`
