### ISSUE TITLE
模拟器底部的虚拟键区域变白了

### ISSUE THREAD

**Issue by iceAnson** [laobie/StatusBarUtil#23]

**Comment by laobie** [comment]
能具体说下怎么使用会出现这个情况么

**Comment by linzhongshu** [comment]
设置：getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE)，虚拟键盘打开时，键盘上方变白

**Comment by iceAnson** [comment]
已经找到原因了，我的baseAcgtivity继承的是FragmentActivity，改成AppCompatActivity就可以了，应该兼容包的要求吧。

**Comment by iceAnson** [comment]
done
