### ISSUE TITLE
设置状态栏透明后，根布局的 padding 属性不生效

### ISSUE THREAD

**Issue by sivan67** [laobie/StatusBarUtil#26]
在代码中设置状态栏透明后
```java
        StatusBarUtil.setTranslucent(this);
```
or
```java
        StatusBarUtil.setTranslucent(this, 0);
```
此 activity 对应的布局文件中根布局的 padding 属性不生效
- 设备：Nexus 5
- 系统：Android 5.1.1
- 根布局：LinearLayout

**Comment by laobie** [comment]
这个确实是这样的，只能在布局上作调整了

**Comment by laobie** [comment]
@sivan67 我试了下，这个暂时确实没办法解决

**Comment by sivan67** [comment]
@laobie 好的。只能改一下布局了

**Comment by laobie** [comment]
@sivan67 这个问题我看了下不好修复，所以暂时关闭了哈
