### ISSUE TITLE
使用DrawerLayout侧滑出来的界面布局上移了,下面是布局代码

### ISSUE THREAD

**Issue by Swordce** [laobie/StatusBarUtil#27]
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/id_drawerLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <com.zhy.autolayout.AutoLinearLayout
        android:id="@+id/main"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <com.zhy.autolayout.AutoRelativeLayout
            android:layout_width="match_parent"
            android:layout_height="108px"
            android:background="@color/white">

            <com.zhy.autolayout.AutoLinearLayout
                android:id="@+id/btn_siding"
                android:layout_width="72px"
                android:layout_height="match_parent"
                android:orientation="horizontal"
                android:gravity="center_vertical">
                <Button
                    android:layout_width="38px"
                    android:layout_height="39px"
                    android:background="@drawable/personal"
                    android:onClick="OpenLeftMenu"
                    android:layout_marginStart="10dp"
                    android:layout_centerVertical="true"
                    android:layout_alignParentStart="true" />
            </com.zhy.autolayout.AutoLinearLayout>

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textColor="@color/black"
                android:textSize="36px"
                android:text="@string/home_title"
                android:layout_centerVertical="true"
                android:layout_centerHorizontal="true"/>
        </com.zhy.autolayout.AutoRelativeLayout>
        <include layout="@layout/activity_bottom"/>
        <FrameLayout
            android:id="@+id/home_content"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp">
        </FrameLayout>
    </com.zhy.autolayout.AutoLinearLayout>

    <fragment
        android:id="@+id/id_left_menu"
        android:name="com.bagevent.home.fragment.MenuLeftFragment"
        android:layout_width="250dp"
        android:layout_height="match_parent"
        android:layout_gravity="left"
        android:tag="LEFT" />

</android.support.v4.widget.DrawerLayout>

**Comment by laobie** [comment]
这个就是上移的，占据包含状态栏界面的，你如果需要不上移的话，自己加一下 margin-top 或者 padding-top
