### ISSUE TITLE
Fragment切换statusbar

### ISSUE THREAD

**Issue by itdais** [laobie/StatusBarUtil#28]
现在有四个Fragment来回之间的切换,首页的顶部是图片需要扩展到状态栏,就是沉浸式状态栏,但是其他的都是colorPrimary的颜色状态栏,,应该如何实现呢

**Comment by YumikoAzu** [comment]
试试fragment切换后 手动调用更改statusbar的方法

**Comment by laobie** [comment]
@itdais 首页的图片可能比较麻烦点，可能需要把图片写在 activity 的布局中，然后你的 fragment 切换时，调用不同的 statusbarutil 的方法来实现不同的效果

**Comment by YumikoAzu** [comment]
CoordinatorLayout 的bug fix了没？ @laobie

**Comment by laobie** [comment]
@YumikoAzu 尝试了下 没修好😂 着急不

**Comment by YumikoAzu** [comment]
http://blog.csdn.net/u013260551/article/details/51150336  看看这个 @laobie

**Comment by laobie** [comment]
@YumikoAzu 这个看起来不错😂 能解决你那个问题么

**Comment by itdais** [comment]
@YumikoAzu @laobie Fragment的切换我本来想用onHideChange 或者onVisiableToUse的方法,发现这两个方法在onCreateView前调用,经过处理后是可以实现statusbar的切换的,但是statusbar的在fragment显示时会有闪一下的情况

**Comment by laobie** [comment]
@itdais 我写了个你这样需求的demo 你可以看下最新的demo了

**Comment by itdais** [comment]
@laobie 可以实现了!非常感谢

**Comment by laobie** [comment]
@itdais 不客气~
