### ISSUE TITLE
小米 Android 4.4.4 系统 状态栏下面多了一块白色区域

### ISSUE THREAD

**Issue by hui453694187** [laobie/StatusBarUtil#29]
![image](https://cloud.githubusercontent.com/assets/5575890/17237301/fefd373e-5582-11e6-8eca-f7f449fde1b4.png)

在5.0的系统上面就没有，请问这怎么解决？

**Comment by laobie** [comment]
布局文件代码贴一下
@hui453694187

**Comment by hui453694187** [comment]
感谢 @laobie  指点
白色那块是因为actionBar 隐藏的问题
在代码中 
```
ActionBar ab = this.getSupportActionBar();
if (ab != null) {
        ab.hide();
}
```
在小米 4.4系统下没完全隐藏，会有个白块
现在在主题中设置 
```
 <item name="windowNoTitle">true</item>
 <item name="windowActionBar">false</item>
```
白带消失了.......
