### ISSUE TITLE
在界面启动的时候会闪现黑色的状态栏 然后才会渲染成设置颜色

### ISSUE THREAD

**Issue by wangchenghao** [laobie/StatusBarUtil#3]

**Comment by laobie** [comment]
这个目前确实存在，因为是在setContentView之后设置的。
如果是app启动的话，可以考虑还是设置下主题里的 colorPrimaryDark（只在5.0以上生效） ，或者加个启动页来解决这个了。

**Comment by wangchenghao** [comment]
还有一个问题请教下，就是关于你demo的transparent和transLucent，这两种模式在界面表现上我看没有什么区别呀 ，我在网上搜索了下，大部分也都是cv的，望指点下，感谢~

**Comment by laobie** [comment]
一个是半透明的（有个遮罩层），一个是全透明的
