### ISSUE TITLE
StatusBarUtil.setColor无法改变4.4miui状态栏颜色

### ISSUE THREAD

**Issue by tyq9702** [laobie/StatusBarUtil#31]
StatusBarUtil.setColor(this, R.color.red)好像对4.4的miui无效，状态栏还是黑的

**Comment by laobie** [comment]
@tyq9702 需要的是颜色值，不是颜色的id 请测试下 demo 正常不，正常的话就是你使用方法问题

**Comment by tyq9702** [comment]
@laobie Get~Thanks！
