### ISSUE TITLE
我在build.gradle开启vectorDrawables.useSupportLibrary = true后报空指针

### ISSUE THREAD

**Issue by Harris-wu** [laobie/StatusBarUtil#33]
defaultConfig {        
        vectorDrawables.useSupportLibrary = true
}
报错地方：
 private static void setRootView(Activity activity) {
        ViewGroup rootView = (ViewGroup) ((ViewGroup) activity.findViewById(android.R.id.content)).getChildAt(0);
        rootView.setFitsSystemWindows(true);
        rootView.setClipToPadding(true);
    }
这里拿不到根布局了

**Comment by laobie** [comment]
@Harris-wu 确定下你是在 setContentView 之后调用的设置状态栏相关的方法么？

**Comment by Harris-wu** [comment]
不好意思，之前因为自己弄了一个状态栏管理工具 一直是在setContentView之前调用的，抱歉，非要仔细阅读说明

**Comment by Harris-wu** [comment]
问题已经解决，就是调用api需要在setContentView之后
感谢博主的解答

**Comment by laobie** [comment]
@Harris-wu ok，下次记得仔细看下文档
