### ISSUE TITLE
4.4系统在切换fragment时改变状态栏有问题

### ISSUE THREAD

**Issue by a404318964** [laobie/StatusBarUtil#34]
首页用的图片，其他三个fragment用的颜色，发现切换到其他界面后在切回首页，图片有部分会被不见掉。debug看了一下，第一次进来，调用clearPreviousSetting方法时，不会调用以下代码
``` java
if (count > 0 && decorView.getChildAt(count - 1) instanceof StatusBarView) {
            decorView.removeViewAt(count - 1);
            ViewGroup rootView = (ViewGroup) ((ViewGroup) activity.findViewById(android.R.id.content)).getChildAt(0);
            rootView.setPadding(0, -getStatusBarHeight(activity), 0, 0);
        }
```
所以显示正常。
切换到其他界面在切回首页时，会调用上面的代码，导致paddingTop是负数，图片上移，所以看起来上面有部分不见了。
修改为rootView.setPadding(0, 0, 0, 0);后发现可以用了

**Comment by laobie** [comment]
你在切换到后三个 Fragment 是否调用了 setColor 方法，我的demo在你那边正常不？

**Comment by a404318964** [comment]
@laobie 
调用了，demo也不正常，华为机子，4.4系统。paddingTop改为置为0后就正常了

**Comment by laobie** [comment]
@a404318964 你测试下模拟器上正常不，我这边测试了模拟器4.4 正常的

**Comment by a404318964** [comment]
@laobie 我这边没4.4的模拟器，我下载一个试试再告诉你结果

**Comment by hyr0318** [comment]
请问，你是怎么在fragment 里面实现图片的沉浸额？我的项目里面图片的那个fragment一直不能沉浸，颜色的fragment 没有问题。是什么原因额？

**Comment by a404318964** [comment]
@hyr0318 作者的demo里面有啊，我跟着作者的demo整的，你下他的demo看下。里面有个use in fragment，里面就是第一个fragment使用图片沉浸，其他的fragment使用颜色

**Comment by laobie** [comment]
@a404318964 ok

**Comment by hyr0318** [comment]
@a404318964  请问 我的项目中不是用fragment+viewpager  是用fragment+Fragmentlayoutz做的切换fragment，demo 里面onPageSelected 的切换应该在我项目里面下面按钮点击事件里面怎么写额？

**Comment by hyr0318** [comment]
@a404318964  @laobie  还有我的图片的fragment 状态栏是灰色的。

**Comment by a404318964** [comment]
@laobie 用Genymotion下了4.4的模拟器，demo一样有问题啊，你仔细看看，从其他fragment切换回来，第一个fragment中的图片明显会上移。这是由于paddingTop设为负的statusbar的高度导致的

**Comment by laobie** [comment]
@a404318964 确实有问题，我的图有点大，没注意到这个= =
已经发布1.2.4 版本修复此 bug
@a404318964 感谢发现 bug

**Comment by laobie** [comment]
@a404318964 麻烦你测试下后，如果没问题的话，关闭下 issuse 哈

**Comment by laobie** [comment]
@hyr0318 你的问题你需要参考下 demo 示例自己来解决下了，思路是一样的，具体的代码得自己写了

**Comment by hyr0318** [comment]
@laobie  大神，上面那个bug测试了没有问题了。 现在我在我项目中使用，只有两个fragment（一个图片，一个颜色），第一次进颜色的fragment 状态栏是灰色的，切换到图片的fragment中，图片的fragmetn也是灰色，再次切换到颜色的fragment 状态栏颜色正常，再切换到图片的也正常，这个是什么原因额，代码是按照demo里面写的额。

**Comment by laobie** [comment]
@hyr0318 你的和 demo 不完全一样，需要变通

**Comment by hyr0318** [comment]
@laobie  嗯，就是切换时候可以看到有一个过程从灰色变成图片的颜色的一个过程。而不是切换就是图片颜色

**Comment by laobie** [comment]
@hyr0318 这个应该是没法避免的 第一次进来的你再调调看看

**Comment by hyr0318** [comment]
@laobie  嗯，就第一次切换到图片的fragment灰看到颜色变换的过程，再切换就不会看到这个变换过程，大神，有QQ群的么，我发个demo的小视频你看看效果

**Comment by laobie** [comment]
@hyr0318 254158532 我qq
