### ISSUE TITLE
我的是华为手机，运行Demo之后 状态栏并没有任何改变，这是怎么回事？

### ISSUE THREAD

**Issue by nick-zeng** [laobie/StatusBarUtil#37]

**Comment by laobie** [comment]
提供下你的 emui 版本和 Android 版本，很大可能是 emui 改了系统相关组件，没法支持到

**Comment by nick-zeng** [comment]
我的  系统版本号是  EMUI  3.1    安卓版本是：5.0.2

**Comment by nick-zeng** [comment]
大神   有QQ 群可以加一下吗

**Comment by nick-zeng** [comment]
我之前用的别人的  修改状态栏的库都没任何问题的  因为项目要修改fragment的状态栏颜色  所有只能用你这个才可以实现了呢

**Comment by laobie** [comment]
@nick-zeng qq 254158532

**Comment by laobie** [comment]
看 #1 这里的回复，目前华为自家改 ROM 改了很多的，暂不支持。
