### ISSUE TITLE
statusbar textcolor  how to change?

### ISSUE THREAD

**Issue by yanglichuan** [laobie/StatusBarUtil#41]
because statusbar textcolor  is white 

but my app primarycolor is also white

**Comment by laobie** [comment]
Only API >= 23, it is also 6.0, you can change StatusBar icon color and TextColor. 
And if you using xiaomi or meizu phone, you may change  StatusBar icon color and TextColor, even API < 23.
you can view this article https://www.aswifter.com/2015/12/24/android-m-change-statusbar-textcolor/

I advice you set StatusBar gray, not white, just set alpha value not 0.
