### ISSUE TITLE
 CoordinatorLayout 为根布局

### ISSUE THREAD

**Issue by csgsky** [laobie/StatusBarUtil#44]
CoordinatorLayout 为根布局的时候，貌似有问题，没有效果

**Comment by laobie** [comment]
用的那个方法，具体说一下，设置透明的话有个专门的方法
`setTranslucentForCoordinatorLayout(Activity activity, int statusBarAlpha)`

**Comment by csgsky** [comment]
问题解决了，谢谢

**Comment by laobie** [comment]
@csgsky ok，那我关闭咯
