### ISSUE TITLE
CoordinatorLayout为根布局，Toolbar偏上

### ISSUE THREAD

**Issue by zhufengweihai** [laobie/StatusBarUtil#45]
如题，怎么解决？

**Comment by laobie** [comment]
@zhufengweihai 截图看看，贴一下代码

**Comment by zhufengweihai** [comment]
![image](https://cloud.githubusercontent.com/assets/22727918/19221056/daf036c4-8e6d-11e6-842f-d9f219bfe2e4.png)

`<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
                                                 xmlns:app="http://schemas.android.com/apk/res-auto"
                                                 xmlns:tools="http://schemas.android.com/tools"
                                                 android:id="@+id/rootView"
                                                 android:layout_width="match_parent"
                                                 android:layout_height="match_parent"
                                                 android:background="@drawable/background_for_default"
                                                 tools:context=".WeatherForecastActivity">

    <android.support.design.widget.AppBarLayout
        android:id="@+id/weather_app_bar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="@android:color/transparent"
        android:theme="@style/AppTheme.AppBarOverlay"
        app:elevation="0dp">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            app:popupTheme="@style/AppTheme.PopupOverlay">

            <ImageView
                android:id="@+id/addCityButton"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:paddingRight="10dp"
                android:src="@mipmap/ic_add_city"/>

            <TextView
                android:id="@+id/cityView"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="青岛"
                android:textColor="@android:color/white"
                android:textSize="20sp"/>

            <ImageView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="end"
                android:paddingRight="15dp"
                android:src="@mipmap/ic_share"/>
        </android.support.v7.widget.Toolbar>
    </android.support.design.widget.AppBarLayout>

    <include layout="@layout/content_weather_forecast"/>

</android.support.design.widget.CoordinatorLayout>`

**Comment by laobie** [comment]
@zhufengweihai 你调用的哪个方法

**Comment by zhufengweihai** [comment]
@laobie StatusBarUtil.setTranslucentForCoordinatorLayout(this, 0);

**Comment by zhufengweihai** [comment]
貌似改成<android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:fitsSystemWindows="true"
            app:popupTheme="@style/AppTheme.PopupOverlay">

能正确显示O(∩_∩)O~

**Comment by laobie** [comment]
啊 我还没测试出来，如果可以的话，我明天在 readme 中加一下

**Comment by zhufengweihai** [comment]
@laobie 我试了一下，不再偏上了，你可以自测一下试试。O(∩_∩)O~

**Comment by laobie** [comment]
@zhufengweihai 好哒，感谢反馈

**Comment by zhufengweihai** [comment]
客气应该的，还得感谢你这么好用的库呢。试了很多方法才找到你这个库

**Comment by laobie** [comment]
@zhufengweihai 写了这么多 Bug 不好意思啊 😂

**Comment by zhufengweihai** [comment]
这一块确实比较复杂，有点bug很正常。O(∩_∩)O~
