### ISSUE TITLE
在华为emui3系统android5上运行时状态栏无反应

### ISSUE THREAD

**Issue by 1371030** [laobie/StatusBarUtil#46]
在华为emui3系统android5上运行时状态栏无反应

**Comment by laobie** [comment]
看看这两个 issue，由于华为自己改动太多，或者说是改版本号升级系统的，没法做兼容
#1 #37

**Comment by 1371030** [comment]
谢谢，在网上找了一圈也没有用反射做华为emui兼容的方法，以后有相关资料再学习

**Comment by laobie** [comment]
@1371030 其实每个方法都有个 xxDiff 方法，虽然我标记为弃用了，但是应该能兼容华为的，你可以试试
