### ISSUE TITLE
魅族Note3状态栏切换颜色随机换

### ISSUE THREAD

**Issue by StudyLifeTime** [laobie/StatusBarUtil#48]
魅族Note3机型 
` StatusBarUtil.setColor(MainActivity.this, Color.BLACK);`
 设置后颜色时灵时不灵,有时候黑色,有时候透明,
开始进入是可以,A进入B页面,B页面顶部用的Imageview
`StatusBarUtil.setTranslucentForImageView(this, 0, mRlayoutNoteDetailTop);`
B返回到A页面,然后A的状态栏变为透明色,
我在A页面的OnResume也设置了
` StatusBarUtil.setColor(MainActivity.this, Color.BLACK);`
还是不可以!!

**Comment by laobie** [comment]
@StudyLifeTime 你测试下 我的 demo 正常不

**Comment by laobie** [comment]
@StudyLifeTime 需要你反馈下结果= =
