### ISSUE TITLE
询问项目内的一个第三方库

### ISSUE THREAD

**Issue by Yanqilong** [laobie/StatusBarUtil#49]
大圣，在Fragmen内使用StatusBarUtil案例中，底部菜单栏所使用的是一个第三方库（bottom-navigation-bar），有源码地址吗？请告知

**Comment by laobie** [comment]
@Yanqilong 
[Ashok\-Varma/BottomNavigation: This Library helps users to use Bottom Navigation Bar \(A new pattern from google\) with ease and allows ton of customizations](https://github.com/Ashok-Varma/BottomNavigation)
其实在 sample 下的 build.gradle 中你就可以看到我用了哪些库的
