### ISSUE TITLE
华为荣耀7 修改颜色失效

### ISSUE THREAD

**Issue by qinyang1018** [laobie/StatusBarUtil#50]
系统5.0.2

**Comment by laobie** [comment]
华为修改了系统相关的 API，不会为其特殊处理。如果 demo 运行也不正常的话，那就无法支持。

**Comment by qinyang1018** [comment]
<img width="274" alt="qq20161020-0 2x" src="https://cloud.githubusercontent.com/assets/15726024/19545671/b475a998-96ba-11e6-822c-71e8fcda61ac.png">

**Comment by qinyang1018** [comment]
demo确实也是失效的，不过华为的mate8是正常的

**Comment by laobie** [comment]
@qinyang1018 没记错的话，华为的 emui 3.x 版本是全局都是这种蓝色的状态栏，无法修改的，4.x 版本是原生 4.4 版本的效果，即使他的 Android 版本可能是 6.0 或者 5.0
#1 #46  中也是这个问题，实在没法理解华为为嘛改动这个 api ，估计他们认为这样比较好看吧，无法理解

**Comment by qinyang1018** [comment]
恩  刚才出问题的是3.x的  现在国内的厂商都大幅度的去改API   加大了国内开发者的难度

**Comment by qinyang1018** [comment]
不过有的app确实适配了  不知道他们怎么做的？  难道是单独针对EMUI3.X做的适配

**Comment by laobie** [comment]
@qinyang1018 每个方法都有个 xxxDiff 方法，你可以试试这个，这个应该是可以的，不会直接使用相关的 5.0 以上的 API

**Comment by qinyang1018** [comment]
好的  我到时尝试下   如果你这面有更好的办法 麻烦告知下  谢谢了

**Comment by laobie** [comment]
@qinyang1018 更好的办法那就需要针对手机型号，判断是不是华为手机，然后 EMUI 版本来处理，说实话，这种工作真的不该做了，华为这种 ROM ，自生自灭好了😂

**Comment by qinyang1018** [comment]
哈哈   同感   国产厂商乱来的都该自生自灭
