### ISSUE TITLE
为什么我的魅族状态栏总有一层黑色的阴影，好烦，和下面的titleView有明显的分界线

### ISSUE THREAD

**Issue by mrchenmo** [laobie/StatusBarUtil#55]

**Comment by laobie** [comment]
@mrchenmo  
贴一下你的项目运行时截图 和 demo 运行时截图，以及你使用的代码，不然我没法给你一个解答

**Comment by laobie** [comment]
如果是你说的那个半透明遮罩的话，有个 statusAlpha 参数可以调整的

**Comment by mrchenmo** [comment]
我已经解决了，谢谢

2016-10-31 16:31 GMT+08:00 Jaeger <notifications@github.com>:
