### ISSUE TITLE
想法：能不能考虑下状态栏底色为白色的情况下，让状态栏字体灰色的适配。

### ISSUE THREAD

**Issue by niniloveyou** [laobie/StatusBarUtil#58]

**Comment by laobie** [comment]
@niniloveyou 
改变状态栏图标的颜色就 6.0 才开始提供了 api 来修改，低版本上没法兼容，因此建议不要使用纯白色的状态栏，如果实在需要的话，开发者可以自行实现，本项目暂时不考虑这个

**Comment by niniloveyou** [comment]
的确只有6.0+ miui6.0+ flyme4.0+ 才可以用
