### ISSUE TITLE
用你的demo测试oppo android4.4.4系统的，状态栏无效？

### ISSUE THREAD

**Issue by Destiny01** [laobie/StatusBarUtil#61]
用你的demo测试oppo android4.4.4系统的，状态栏无效？

**Comment by laobie** [comment]
@Destiny01 那就是 oppo 的系统问题，没法兼容的

**Comment by Destiny01** [comment]
好的谢谢！

**Comment by heiyl** [comment]
这个还和ROM有关呀，我自己实现了一次，oppo android 4.4.4的是可以实现沉浸式效果的

**Comment by laobie** [comment]
@heiyl 可能有一些方法可以做到，但是我不想因为国产 rom 自己改动很多东西来写这些兼容代码，这在我看来是没有必要的。
