### ISSUE TITLE
状态栏和虚拟按键自动进入界面后，自动隐藏问题

### ISSUE THREAD

**Issue by huanting** [laobie/StatusBarUtil#62]
你好，
      非常感谢你开发的这个控件。
      我在使用过程中发现有个问题，如果我想进入界面后，状态栏和虚拟按键，自动隐藏，向内滑动的时候，这2个控件再次显示，现在我测试有问题。
     1、状态栏不会自动隐藏。
     2、如果处理状态栏和虚拟按键自动隐藏，状态栏和toolbar会重叠（DrawerLayout不会重叠，因为上面添加了一个padding，其他的会有。）

**Comment by laobie** [comment]
@huanting 自动隐藏应该是是设置了全屏吧，这应该是有问题的，因为那个状态栏是添加了一个假的 View 上去的，不是真实的状态栏，所以会存在问题的。

**Comment by huanting** [comment]
你好：

    我测试了下，不使用这个开源库。直接全屏显示，在5.0、 4.4和6.0上，状态栏是可以正常显示。

谢谢你的回复

**Comment by laobie** [comment]
@huanting 
确实，所以你这种使用场景的话，需要自己单独处理下了，这个工具类的实现原理是不支持这种场景的。
