### ISSUE TITLE
 StatusBarUtil.setTranslucentForImageView(this, mViewNeedOffset);中，第二个参数有要求吗？

### ISSUE THREAD

**Issue by Destiny01** [laobie/StatusBarUtil#63]
StatusBarUtil.setTranslucentForImageView(this, mViewNeedOffset);中，第二个参数有要求吗？

**Comment by laobie** [comment]
@Destiny01 
看你的界面设计，这个值是防止应为设置了状态栏，导致部分布局上移了一个状态栏高度加上的

**Comment by Destiny01** [comment]
也就是图片下面的布局白

**Comment by laobie** [comment]
@Destiny01 可以这么理解

**Comment by Destiny01** [comment]
如果Toolbar也设置半透明的话，状态栏半透明不起作用？如图：
![screenshot_2016-11-23-09-42-22-628_com tianshengd](https://cloud.githubusercontent.com/assets/11342391/20548769/520dfa64-b161-11e6-8960-d569f8701816.png)

**Comment by laobie** [comment]
@Destiny01 你这状态栏不是设置全透明了么，如果是半透明，你可以传 alpha 参数的

**Comment by Destiny01** [comment]
我看错了，好的谢谢了！
