### ISSUE TITLE
实现视差效果？

### ISSUE THREAD

**Issue by TracesDream** [laobie/StatusBarUtil#65]
设置状态栏半/全透明；使用 ImageView 作为头部的界面设置状态栏半/全透明：

     setTranslucent
     setTransparent
     setTranslucentForImageView
     setTransparentForImageView

如果在ScrollView滑动中，我想要实现Toolbar和StatusBar根据ScrollView的滑动来更改透明或者颜色，以上的方法好像都没有color值，希望作者可以加上，而不单单只是半透明和透明！

**Comment by laobie** [comment]
这个本来是有官方控件的 `CollapsingToolbarLayout`
不过你说的是个问题，我待会看看，其实你也可以提个 pr ，改动也不是很大哈

**Comment by laobie** [comment]
@TracesDream 😂你咋关闭了 等你提 pr 呢，后续我加上也行

**Comment by TracesDream** [comment]
@laobie 感谢您的分享，不提是因为我根据您的库重新做了个库，请见谅！

精简了下代码，功能实现还是和您的一样，实现视差：主要是根据color来实现，直接使用Color.argb来实现视差。

**Comment by laobie** [comment]
@TracesDream 
好吧 本想着你来个 pr 呢😂
