### ISSUE TITLE
FragMent中使用时状态栏闪现白色条

### ISSUE THREAD

**Issue by llizhihong** [laobie/StatusBarUtil#66]
使用的是FragMentManager切换FragMent
1FragMent设置 StatusBarUtil.setTranslucentForImageViewInFragment(activity, null);
2FragMent设置  StatusBarUtil.setColor(activity, getResources().getColor(R.color.colorPrimaryDark));
当从2返回1时会状态栏会闪现白色，然后恢复正常。
demo里的是灰色

**Comment by laobie** [comment]
#53 
@llizhihong  建议看这里的讨论，最后那个方案是最好的解决方法，否则就只能自己解决了

**Comment by llizhihong** [comment]
在布局里面写死View吗？

**Comment by llizhihong** [comment]
@laobie 在布局里面写死View吗？

**Comment by laobie** [comment]
@llizhihong 
我觉得这个讲清楚了 
![image](https://cloud.githubusercontent.com/assets/7184320/20745128/ce13bebe-b71a-11e6-8720-3e20368c80e1.png)

**Comment by llizhihong** [comment]
@laobie 收到，多谢~

**Comment by laobie** [comment]
参照 #53
