### ISSUE TITLE
头部布局与状态栏系统图标重叠显示

### ISSUE THREAD

**Issue by hxxxxxxxk** [laobie/StatusBarUtil#67]
@laobie 大神你好，在BaseActivity中调用StatusBarUtil.setTranslucentForImageViewInFragment(this, 0, null)后，状态栏透明效果出现了，如果头部是图片显示正常，但是头部不只是图片，有title或Button的，会和状态栏的信号图标、电量图标、时间图标等等重叠在一起显示，请问下怎么解决？

**Comment by laobie** [comment]
@hxxxxxxxk 最后一个参数你看下是干嘛的，不要随便就传个 null
