### ISSUE TITLE
华为P9设置StatusBarUtil.setTranslucentForImageView(UserDetailsMessageActivity.this, mStaView);没效果

### ISSUE THREAD

**Issue by xuekaiqi** [laobie/StatusBarUtil#68]
StatusBarUtil.setTranslucentForImageView(UserDetailsMessageActivity.this, mStaView); 最后面的view 是什么意思？ 到地要怎么传递

**Comment by laobie** [comment]
@xuekaiqi 有注释，有参数名。
如果仅仅是华为上有问题，那就是华为系统的问题。

**Comment by xuekaiqi** [comment]
大神您好 ，请问这个开源库有交流群吗?

**Comment by laobie** [comment]
@xuekaiqi 没 = =

**Comment by xuekaiqi** [comment]
或者可以加你QQ吗？

**Comment by laobie** [comment]
@xuekaiqi 254158532
