### ISSUE TITLE
猴哥我是看一个开源项目跟踪到这的,有一个重复设置Bug

### ISSUE THREAD

**Issue by boboyuwu** [laobie/StatusBarUtil#69]
切换时 statusBar的颜色并没有改变，这个问题已经提交给了StatusBarUtil 的作者。

这是作者原话,就是状态栏颜色第一次进来Activity时没问题可以显示,重新设置一下然后reCreateActivity没效果

**Comment by laobie** [comment]
@boboyuwu 不知道这是什么时候的评论呢？中间有修复过这样的一个 bug 
能否贴一下该开源项目的链接？

**Comment by boboyuwu** [comment]
github搜索banya   500多star的那个就是

**Comment by laobie** [comment]
@boboyuwu 应该处理过了= =
