### ISSUE TITLE
与windowSoftInputMode设置成stateHidden | adjustResize冲突

### ISSUE THREAD

**Issue by EvilBT** [laobie/StatusBarUtil#70]
如上，然后布局中有EditText，进入界面之后点击EditText后Resize界面会出现失效的状态，具体你可以看下效果

**Comment by EvilBT** [comment]
已经有相同的issue了，昨晚忘记看了，抱歉

**Comment by laobie** [comment]
@EvilBT 这个问题我得看看咋回事，处理键盘确实比较麻烦
