### ISSUE TITLE
请问有办法实现背景为白色，状态栏字体黑色吗

### ISSUE THREAD

**Issue by Jarvay** [laobie/StatusBarUtil#71]

**Comment by laobie** [comment]
这个自行处理下，有相关说明的，目前除了部分特殊 ROM 和原生 6.0 以外，暂时没法做到完整的 图标变黑色

**Comment by zhoujs** [comment]
https://github.com/chenglei1986/StatusBarColorManager  楼主对于状态栏修改白色可以参看这个项目，增加对小米等手机的适配

**Comment by laobie** [comment]
1.5 版本已经添加设置状态栏模式方法，请更新到最新版本
```
  StatusBarUtil.setLightMode(Activity activity)
  StatusBarUtil.setDarkMode(Activity activity)
```
