### ISSUE TITLE
setTranslucentForCoordinatorLayout 方法在魅族手机上无效

### ISSUE THREAD

**Issue by Object-Ping** [laobie/StatusBarUtil#73]
亲测，在魅族手机上不可用

**Comment by laobie** [comment]
我这边在魅族小米手机上都是可以的，请下载 demo 测试，然后截图，如果有问题，给出机型，系统版本。
你这么提 isuue ，指望我怎么回答你？

**Comment by IAskWind** [comment]
我这边可以，估计用了android support控件，作者曾经给出链接，处理过，关于support控件的问题，自己在issues找下

**Comment by Object-Ping** [comment]
魅蓝metal
系统版本：Flyme os 5.1.0.6QY
型号：M57AC

**Comment by laobie** [comment]
使用我的 demo 截图

**Comment by Object-Ping** [comment]
你的源码里面没有调用setTranslucentForCoordinatorLayout方法。

**Comment by laobie** [comment]
………非要几个回合才说清楚用了哪个方法，没有你贴上布局，贴上代码就是了，再说你这个不行就

**Comment by laobie** [comment]
还有你的标题起的挺大的。

**Comment by Object-Ping** [comment]
![360 1214_11_57_01](https://cloud.githubusercontent.com/assets/10297168/21169321/28f7a634-c1f6-11e6-9843-c8f102d50824.png)
![360 1214_12_08_01](https://cloud.githubusercontent.com/assets/10297168/21169322/29867e90-c1f6-11e6-8c36-8f01595ea001.png)

**Comment by Object-Ping** [comment]
我直接把你那两个文件拷到我的项目里了！

**Comment by laobie** [comment]
@Object-Ping 这个和系统相关了，建议你改变下布局，最外层套一个 FrameLayout 之类的来解决，setTranslucentForCoordinatorLayout 这个方法主要是针对 CoordinatorLayout  布局，兼容上没完整测试过
