### ISSUE TITLE
关于给 needOffsetView 设置 margin 的建议，可能 needOffsetView 本来就有了左、右、下这三个方向的 margin 值

### ISSUE THREAD

**Issue by bingoogolapple** [laobie/StatusBarUtil#74]
![image](https://cloud.githubusercontent.com/assets/8949716/21209523/c168e27a-c2af-11e6-8260-1fc1415a3a7a.png)

可能 needOffsetView 本来就有了左、右、下这三个方向的 margin 值，例如这种引导页主题没有设置全屏但是又想填充整个屏幕的情况

![image](https://cloud.githubusercontent.com/assets/8949716/21209803/72b587bc-c2b1-11e6-8cca-792448beceea.png)

建议把 setTranslucentForImageView(Activity activity, int statusBarAlpha, View needOffsetView) 方法中的

```java
layoutParams.setMargins(0, getStatusBarHeight(activity), 0, 0);
```

改成

```java
layoutParams.setMargins(layoutParams.leftMargin, layoutParams.topMargin + getStatusBarHeight(activity), layoutParams.rightMargin, layoutParams.bottomMargin);
```

**Comment by laobie** [comment]
@bingoogolapple 1.3.2 已经发布，修复了该问题
