### ISSUE TITLE
关于在fragment中使用的问题

### ISSUE THREAD

**Issue by diorslau** [laobie/StatusBarUtil#75]
你好,我看了一下关于fragment中使用的代码,发现其实并非真正的实现的沉侵的效果吧,如果我fragment中顶部是个toolbar  然后toolbar的背景是透明的,好像就实现不了效果吧.

还有我想请教个问题,  我之前自己也试了很多次  我发现在activity中初始化的时候我把fragment add进去的话这时候再fragment中设置的fitsystem是有效的  但是通过其他事件动态add进去后  fitsystem貌似就无效了,不知道这个是什么意思呢?

**Comment by laobie** [comment]
第一个问题可以的啊，不知道你要的是啥效果，目前看来实现应该是没问题的。

至于第二个的话，其实状态栏相关的操作都是针对 activity 来的，和 Fragment 关系不大，无非是在 Fragment 中调用 Activity 对应的方法来设置而已。
