### ISSUE TITLE
gradle import 拼写错误

### ISSUE THREAD

**Issue by icyfox-bupt** [laobie/StatusBarUtil#77]
compile 'com.jaeger.statusbaruitl:library:1.3.2'

其中的 statusbar**uitl** 拼写错误

建议改个名字，然后开两个并行的import暂时..

**Comment by laobie** [comment]
@icyfox-bupt 已知问题，但是两个并行的话后面升级比较麻烦，考虑到之前的版本一个个升级的成本太大，暂时先不处理了，

**Comment by laobie** [comment]
@icyfox-bupt 最新的版本 1.4.0 中已经修改过来了，目前两个可以同时使用
