### ISSUE TITLE
使用autolayout之后迷之显示

### ISSUE THREAD

**Issue by AlexFugui** [laobie/StatusBarUtil#78]
我集成了com.zhy:autolayout:1.4.5再用StatusBarUtil 界面会有迷之位移 actionbar被隐藏但是占用布局 屏幕下方会出现状态栏等高的白色

**Comment by AlexFugui** [comment]
@laobie 不会传图 见谅

**Comment by laobie** [comment]
@AlexFugui 
直接复制图片粘贴上来即可，还有你这个问题，应该是和 AutoLayout 配合使用的问题，需要自行排查

**Comment by AlexFugui** [comment]
![qq 20161219130313](https://cloud.githubusercontent.com/assets/22453816/21302412/95a5d158-c5f1-11e6-959b-8dd760b5be67.png)
![qq 111](https://cloud.githubusercontent.com/assets/22453816/21302466/060dd526-c5f2-11e6-9842-39a8859a8547.png)

下方白条应该就是autolayout的锅吧 应该是整个布局少了状态栏的高度
setContentView之前我调用了getSupportActionBar().hide();
做开发不久...不知道这个问题能解决么 谢谢大腿
@laobie

**Comment by laobie** [comment]
对 AutoLayout 了解不多，其实那个颜色状态栏也是一个 View 添加到布局中的，这个肯定改动大了，我的建议，两者只用其一。适配的问题，官方的布局肯定能解决的。

**Comment by AlexFugui** [comment]
@laobie 
好的 谢谢大腿 能解决兼容问题我会发出的
