### ISSUE TITLE
参照demo写的，状态栏顶部的时间和wif信号都没显示，这个是啥问题的呀？

### ISSUE THREAD

**Issue by yuxingfafu** [laobie/StatusBarUtil#79]
参照demo写的，状态栏顶部的时间和wif信号都没显示，这个是啥问题的呀？

**Comment by laobie** [comment]
@yuxingfafu 你设置了白色吧

**Comment by laobie** [comment]
@yuxingfafu 白色状态栏需要自己修改图标颜色的，这个你搜搜就能找到解决办法的

**Comment by yuxingfafu** [comment]
好，我试下。非常感谢，我是设置成了白色的了

**Comment by yuxingfafu** [comment]
http://www.jianshu.com/p/7f5a9969be53
猴哥，能否把这个就是白色的背景的时候，状态栏背景颜色白色修改的也添加进去？

**Comment by laobie** [comment]
@yuxingfafu 可以单独加个方法，setStatusBarIconColor 😂 等我明天看下怎么加 你也可以提个 pr 的
