### ISSUE TITLE
在fragment的显示问题

### ISSUE THREAD

**Issue by jiang330227** [laobie/StatusBarUtil#80]
您好,我是用fragmentManger切换fragment的,我的第四个fragment是沉浸式图片,前三个fragment只是沉浸式颜色,当我进入app,直接点第四个fragment,然后再点第二个fragment时,整体布局就向上移动了,然后点击别的fragment后再点击第二个fragment,又恢复正常了,请问,这是什么原因导致的呢

**Comment by laobie** [comment]
@jiang330227 Fragment 中的使用问题，建议看这个下面的讨论
#53

**Comment by laobie** [comment]
>可以给你其他fragment的最上面添加一个View
<View
android:background="@color/main_red" //你想设置的颜色
android:layout_width="match_parent"
android:layout_height="@dimen/statusbar_height"/> //状态栏的高度

之后在values-v19 dimens.xml中定义statusbar_height = 25dp
在vlues 下定义statusbar_height = 0dp
意为API>=19以上高度为25dp(状态栏高度) 以下高度为0dp

**Comment by laobie** [comment]
@jiang330227 如果不这么处理，你得看下我那个界面怎么写的，你的位置和我的不一样，处理起来也不一样的

**Comment by jiang330227** [comment]
谢谢了

**Comment by laobie** [comment]
@jiang330227 

更新了英文的 README 详细介绍了在 Fragment 中使用的方法，对应的 Demo 也更新了，可以下载查看。如果没疑问了，请关闭此 issue。
