### ISSUE TITLE
vivo Y27 无效

### ISSUE THREAD

**Issue by ncworm** [laobie/StatusBarUtil#86]
vivo Y27 设置StatusBarUtil.setTranslucent后，跳转过去后闪一下透明后又变回白色状态栏

**Comment by laobie** [comment]
下载 Demo 测试下看看是不是也存在这个问题

**Comment by ncworm** [comment]
无效。系统版本4.4.4

**Comment by laobie** [comment]
那就可能是 vivo 改了 Rom，和华为类似的情况，这个没法做兼容了呢
