### ISSUE TITLE
Hisense E70-T 无效

### ISSUE THREAD

**Issue by recwert** [laobie/StatusBarUtil#88]
感谢写了这么棒的库给大家用。
我这边发现我这的一台测试机 Hisense E70-T StatusBarUtil.setTransparent(this);无效
但是我在这台测试机上使用QQ的时候，QQ是实现了全透明了。不知道是怎么实现的。

**Comment by laobie** [comment]
你试试看 demo 呢

**Comment by recwert** [comment]
@laobie demo我试过了，所有的功能全部失效，估计是这个ROM被改了，好奇的是我看这个手机里的其他几个应用实现了沉浸式，比如”QQ“，”设置“是实现了。”微信“在这台机子上也没有实现

**Comment by recwert** [comment]
@laobie 有个功能想请教下，我实际想实现的是全透明，然后在toolbar上放一个状态栏高度那么高的图片，这样就可以让让状态栏用我的图片为背景，但是现在估计像Hisense E70-T（Android 5.1）这种机型挺多的，我没有办法判断出这种机型然后把沉浸式去掉，如果只是单纯的判断Android 4.4的话，多写个layout就可以了。像这种定制ROM要怎么适配？

**Comment by laobie** [comment]
这种还真不好弄，也不知道 qq 是怎么做的，这种自家改动太多的 rom 没法做到完全的完美的适配的
