### ISSUE TITLE
setTranslucentForCoordinatorLayout能不能不要让底部虚拟导航栏也透明

### ISSUE THREAD

**Issue by asker517** [laobie/StatusBarUtil#90]
RT,修改activity.getWindow().addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION); clean了上面状态栏就又会有问题..

**Comment by laobie** [comment]
这个不好兼容，暂时不会考虑这个

**Comment by asker517** [comment]
@laobie 哦 好吧 感谢
