### ISSUE TITLE
播放器全屏播放时无法隐藏status bar

### ISSUE THREAD

**Issue by coofeeing** [laobie/StatusBarUtil#91]
播放器全屏播放时无法隐藏status bar，可不可以提供个方法，隐藏呢？

**Comment by laobie** [comment]
这个应该是全屏或者添加一些 Flag 去实现的

**Comment by coofeeing** [comment]
已经设置了flag，标题栏已经隐藏，但是顶部还有个”条”不能隐藏

**Comment by coofeeing** [comment]
我使用的是setColorForDrawerLayout这个方法，使用其他方法则没这个问题

**Comment by laobie** [comment]
能截个图不？

**Comment by coofeeing** [comment]
这个地方貌似没法传图片啊

**Comment by laobie** [comment]
直接复制 这里粘贴就行，或者外链 markdown 图片写法

**Comment by laobie** [comment]
![image](https://cloud.githubusercontent.com/assets/7184320/21802369/6cf8bc40-d760-11e6-905f-3942fbebc23c.png)

**Comment by gdmec07140541** [comment]
就是出现这种情况：https://github.com/gdmec07140541/TestDemo/blob/master/app/src/main/res/mipmap-hdpi/Screenshot_2017-01-11-12-23-42.png，在android4.4上出现，5.0以上没有这种问题，还有一个问题就是加了FAB，自定义behavior原本是可以向下滑动隐藏，向上滑动出现的，加了这个库后，向下滑动隐藏了，向上滑动就不出现了。

**Comment by gdmec07140541** [comment]
就是出现这种情况：https://github.com/gdmec07140541/TestDemo/blob/master/app/src/main/res/mipmap-hdpi/Screenshot_2017-01-11-12-23-42.png，在android4.4上出现，5.0以上没有这种问题，还有一个问题就是加了FAB，自定义behavior原本是可以向下滑动隐藏，向上滑动出现的，加了这个库后，向下滑动隐藏了，向上滑动就不出现了。

**Comment by laobie** [comment]
@gdmec07140541 
1. 那个多出来的彩色条隐藏的可以加上
2. 至于你说的向上滑动不出现应该不是这个库导致的

**Comment by gdmec07140541** [comment]
那个色彩怎么隐藏的，那个滑动我去掉这个库就没那个问题了

**Comment by laobie** [comment]
@gdmec07140541 
那个隐藏等我加上方法，滑动的可能是你用的 support 包版本和我库中的不一致导致的 我用的比较新，你自己排查下

**Comment by gdmec07140541** [comment]
好的，谢谢

**Comment by laobie** [comment]
@gdmec07140541 你是什么手机，系统版本多少呢，用的哪个方法？

**Comment by gdmec07140541** [comment]
酷派大神2，android4.4，用的是 StatusBarUtil.setColor(this, color, statusBarAlpha);这方法

**Comment by laobie** [comment]
@gdmec07140541 
@coofeeing 

1.3.5 新增 `hideFakeStatusBarView` 方法，测试反馈下效果

**Comment by gdmec07140541** [comment]
完美解决

**Comment by laobie** [comment]
@gdmec07140541 
![image](https://cloud.githubusercontent.com/assets/7184320/21837268/b613a96c-d805-11e6-87b3-4e507b05dc31.png)

**Comment by coofeeing** [comment]
使用hideFakeStatusBarView 这个方法应该可以解决，我试试~

**Comment by laobie** [comment]
@coofeeing 测试可以了告诉我下

**Comment by coofeeing** [comment]
@laobie 好的！
