### ISSUE TITLE
切换Fragment时底部栏上移？

### ISSUE THREAD

**Issue by Destiny01** [laobie/StatusBarUtil#92]
![default](https://cloud.githubusercontent.com/assets/11342391/21800118/1cf816e0-d757-11e6-9695-ba44767a6d2d.jpg)
![default](https://cloud.githubusercontent.com/assets/11342391/21800119/1cf89624-d757-11e6-81ae-e3ae7f06c0fb.jpg)
![default](https://cloud.githubusercontent.com/assets/11342391/21800121/1d05481a-d757-11e6-85e6-70d17508a919.jpg)
上面是我的app的几个页面前3个statusbar都是颜色，最后一个是图片，但我第一次进来时依次切换时，到最后一个会出现下面底部栏上移的情况？
![default](https://cloud.githubusercontent.com/assets/11342391/21800120/1cf9d0f2-d757-11e6-9cea-e503a72fc10c.jpg)
使用方式：在MainActivity 开始的时候：StatusBarUtil.setColor(this, getResources().getColor(R.color.colorPrimary), 0);
         if(position==FORTH){
                    isFullScreen = true;
                    StatusBarUtil.setTransparentForImageViewInFragment(MainActivity.this, null);
                }else {
                    if (isFullScreen) {
                        resetFragmentView(mFragments[position]);
                    }
                    StatusBarUtil.setColor(MainActivity.this, getResources().getColor(R.color.colorPrimary), 0);
                }
请问是否我的使用姿势不对？
![default](https://cloud.githubusercontent.com/assets/11342391/21800453/a92b5b9e-d758-11e6-99f2-16700a79a73e.png)
![default](https://cloud.githubusercontent.com/assets/11342391/21800454/a92c10c0-d758-11e6-9538-a7e30754f391.png)

**Comment by laobie** [comment]
查看最新的 Fragment 用法 README 中有

**Comment by Destiny01** [comment]
ok,已解决，谢谢！

**Comment by 531149907** [comment]
请教一下您的圆角图片效果是怎么实现的？Xfermode还是？ 谢谢

**Comment by Msnzz** [comment]
如何解决的
