### ISSUE TITLE
滚动RecyclerView隐藏Toolbar,无法完全隐藏toolbar,会留出一点

### ISSUE THREAD

**Issue by 2391645784** [laobie/StatusBarUtil#93]
如题

**Comment by laobie** [comment]
@2391645784 上图

**Comment by 2391645784** [comment]
![default](https://cloud.githubusercontent.com/assets/19327663/22100197/82c32a00-de69-11e6-8bd7-71bfc5770913.png)

**Comment by 2391645784** [comment]
@laobie 就像图中那样

**Comment by laobie** [comment]
@2391645784 
这个最新版本有个 `hideFakeStatusBarView` 方法可以隐藏这个多余的 View
