### ISSUE TITLE
编译错误，最新版1.3.5版本  找不到'com.android.support:appcompat-v7:25.1.0' 

### ISSUE THREAD

**Issue by v991314** [laobie/StatusBarUtil#94]
我下了demo来看，里面的build.gradle,应该改成25.0.1就不会报错了。  现在最新的才25.0.2，应该是写错了 ，望能及时修改！！

**Comment by v991314** [comment]
1.3.3和1.3.4也有这个问题。现在只有 compile 'com.jaeger.statusbaruitl:library:1.3.2'能用！

**Comment by laobie** [comment]
![image](https://cloud.githubusercontent.com/assets/7184320/22140755/5d00eeae-df29-11e6-8d03-c79db2e192c1.png)

**Comment by laobie** [comment]
@v991314 以后睁眼说瞎话，别怪我直接喷你

**Comment by v991314** [comment]
恩，你是对的，我的问题，我把 buildToolsVersion "25.0.1"和 support:appcompat-v7:25.1.0  弄混了。
