### ISSUE TITLE
CoordinatorLayout 导致ToolBar位置往上移动一部分，采用LinearLayout包裹也没效果

### ISSUE THREAD

**Issue by androidXiaoHao** [laobie/StatusBarUtil#97]
您好，正如题目所说，透明方式采用StatusBarUtil.setTransparentForImageViewInFragment(MainActivity.this,null)的方式，问题和#5五楼的一样，我按照说明用LinearLayout包裹也没效果，还是会上移。

**Comment by laobie** [comment]
setTransparentForImageViewInFragment 有个参照传如 needOffsetView 就是你的 toolbar 即可

**Comment by androidXiaoHao** [comment]
非常感谢您，问题解决了，谢谢~

**Comment by laobie** [comment]
@androidXiaoHao 不客气，那我关闭 issue 了

**Comment by androidXiaoHao** [comment]
嗯，好的，您的框架非常棒
