### ISSUE TITLE
状态栏设置颜色后，透明度不起效果

### ISSUE THREAD

**Issue by Yanqilong** [laobie/StatusBarUtil#98]
举个例子 R.color.colorAccent是粉红色， 当透明度设置为0时，状态栏还是粉红色（原色），  透明度为255时为黑色，为什么透明度0是透明的，  255是粉色呢？

//实际效果
StatusBarUtil.setColor(this, R.color.colorAccent,  0);  //粉色
StatusBarUtil.setColor(this, R.color.colorAccent,  255); //黑色

**Comment by laobie** [comment]
最后那个是半透明的遮罩层，Android 原生的 toolbar 和 状态栏 是有色差的，状态栏多一个半透明的遮罩，如果你不需要这个半透明的遮罩的话，传 0 即可

**Comment by deepsadness** [comment]
这个是要布局为DrawerLayout才行吗？我改成了DrawerLayout，并调用seekbar里面的方法。确实做到了没有半透明的遮罩。如果不用DrawerLayout。我要怎么做呢
