### ISSUE TITLE
华为手机荣耀4A，android5.1，demo没用

### ISSUE THREAD

**Issue by GuoZhaoHui628** [laobie/StatusBarUtil#99]
你好，我在如题所示的手机上运行你github的sample但是没用，并没有状态栏沉浸，见图片。如果知道麻烦指导下，谢谢大佬了.话说大佬有Q群没
![qq 20170209110058](https://cloud.githubusercontent.com/assets/22516934/22767570/190ac222-eeb7-11e6-8911-48fe0ccd49ef.png)
![qq 20170209110112](https://cloud.githubusercontent.com/assets/22516934/22767574/21c2fa38-eeb7-11e6-8679-54e5a608e789.png)

**Comment by laobie** [comment]
华为 rom 支持是由问题的，他们系统改动太多 没有 qq 群也

**Comment by GuoZhaoHui628** [comment]
谢谢解答了
